# server setting
server:
  port: 8083 # port setting
  servlet:
    context-path: /auth # 시작 path 셋팅

# spring setting
spring:
  application: #application 명
    name: oauth2 
  devtools: #devtools 설정
    livereload:
      enabled: true
  datasource: #postgreSQL
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: wsl659372
  jpa: # 해결책에 의한 jpa 추가 => https://ryudaewan.wordpress.com/2018/02/08/pgsql_jpa/
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false    
          
#대칭키
signing:
  key: '345345fsdgsf5345'
  
